accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path('signup/', views.SignupView.as_view(), name="signup"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path("edit_profile/", views.EditProfileView.as_view(), name="edit_profile"),
]

buyer/urls.py
from django.urls import path
from .views import (BuyerHomeView, VegetableListView, ProductDetailView,
                    PurchaseCompleteView, TransactionListView, TransactionDetailView,
                    GenreFirstView, GenreVegetableView, GenreDetailView, ErrorBCView, NothingProductView)

app_name = "buyer"

urlpatterns = [
    path("home/", BuyerHomeView.as_view(), name="home"),
    path('vegetable_list/', VegetableListView.as_view(), name='vegetable_list'),
    path('product/<int:vegetable_id>/', ProductDetailView.as_view(), name='product_detail'),
    path('genre/', GenreFirstView.as_view(), name='genre'),
    path('genre/genre_vegetable/', GenreVegetableView.as_view(), name='genre_vegetable'),
    path('genre/<str:genre_name>/', GenreDetailView.as_view(), name='genre_name'),
    path('purchase_complete/', PurchaseCompleteView.as_view(), name='purchase_complete'),
    path('transaction_list/', TransactionListView.as_view(), name='transaction_list'),
    path('transaction_list/<int:vegetable_id>/<uuid:transaction_id>/', TransactionDetailView.as_view(), name='transaction_detail'),
    path('blockchain_error/', ErrorBCView.as_view(), name='blockchain_error'),
    path('nothing_purchased_product/', NothingProductView.as_view(), name='nothing_purchased_product'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/accounts/')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('buyer/', include('buyer.urls')),
    path('seller/', include('seller.urls')),
]

seller/urls.py
from django.urls import path

from .views import SellerHomeView, CreateItemView, ProductDetailView, EditItemView

app_name = "seller"

urlpatterns = [
    path("home/", SellerHomeView.as_view(), name="home"),
    path('create/', CreateItemView.as_view(), name='create_item'),
    path('product/<int:vegetable_id>/', ProductDetailView.as_view(), name='product_detail'),
    path('edit/<int:vegetable_id>', EditItemView.as_view(), name='edit_item')
]

seller/models.py
from django.db import models
from accounts.models import User

# 出品者
class Seller(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='seller')
    address = models.CharField(max_length=200)

    def __str__(self):
        return str(self.user_id)


# 商品情報
class Product(models.Model):
    MAIN_GENRE_CHOICES = (
        ('Grains', '穀物類'),
        ('Vegetables', '野菜類'),
        ('Fruits', '果物類'),
        ('Others', 'その他'),
    )
    SUB_GENRE_CHOICES = (
        ('---', '---'),
        ('LeafStem', '葉茎菜類'),
        ('Root', '根菜類'),
        ('Fruit', '果菜類'),
        ('Others', 'その他'),
    )

    item_name = models.CharField(max_length=100, primary_key=True)
    main_genre_name = models.CharField(max_length=100, choices=MAIN_GENRE_CHOICES)
    sub_genre_name = models.CharField(max_length=100, choices=SUB_GENRE_CHOICES, blank=True, default='---')

    class Meta:
        permissions = [
            ('can_edit_product', 'Can edit product'),  # 編集権限
        ]

    def __str__(self):
        return f"{self.item_name}"


# 出品商品
class Vegetable(models.Model):
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE, related_name='vegetable')      # 出品者
    item_name = models.ForeignKey(Product, on_delete=models.CASCADE, default=None, null=True)   # 商品
    item_type = models.CharField(max_length=100, default='---')                                 # 品種名
    price = models.DecimalField(max_digits=100, decimal_places=2, default=0)                    # 単価
    content_quantity = models.PositiveIntegerField(default=1)                                   # まとまりの内容個数
    content_price = models.DecimalField(max_digits=100, decimal_places=2, default=0)            # まとまりの価格
    total_quantity = models.PositiveIntegerField(default=0)                                     # まとまりの総数

    def __str__(self):
        return str(self.seller.id)

seller/forms.py
from django import forms
from .models import Vegetable, Product
from django.utils.translation import gettext_lazy as _


class ItemForm(forms.ModelForm):
    item_name = forms.ModelChoiceField(queryset=Product.objects.all(), empty_label=None, label='商品名')

    class Meta:
        model = Vegetable
        fields = ['item_name', 'item_type', 'content_quantity', 'content_price', 'total_quantity']

        # フィールドのラベルを日本語に設定
        labels = {
            'item_type': _('品種名'),
            'content_quantity': _('内容量（個数）'),
            'content_price': _('価格/袋'),
            'total_quantity': _('出品総数'),
        }

seller/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Seller, Vegetable
from accounts.forms import UserProfileForm
from django.views.generic import DetailView
from django.views import View
from .forms import ItemForm

from django.contrib.auth.mixins import LoginRequiredMixin


class SellerHomeView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'  # ログインしていない場合のリダイレクト先URL

    def get(self, request):
        user = request.user.id
        try:
            seller = Seller.objects.get(user_id=user)
            vegetables = Vegetable.objects.filter(seller_id=seller.id)
            form = UserProfileForm()
            return render(request, 'seller/home.html', {'vegetables': vegetables, 'form': form})
        except Seller.DoesNotExist:
            # ユーザが出品者でない場合の処理
            return render(request, 'seller/seller_not_found.html')


class CreateItemView(View):
    template_name = 'seller/create_item.html'

    def get(self, request):
        form = ItemForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = ItemForm(request.POST)
        if form.is_valid():
            item = form.save(commit=False)
            # ログインしているユーザーを出品者と紐付ける
            if request.user.is_authenticated:
                item.seller = request.user.seller
            item.save()
            return redirect('seller:home')
        return render(request, self.template_name, {'form': form})


class ProductDetailView(DetailView):
    model = Vegetable
    template_name = 'seller/product_detail.html'
    context_object_name = 'vegetable'
    pk_url_kwarg = 'vegetable_id'


class EditItemView(View):
    model = Vegetable
    template_name = 'seller/edit_item.html'

    def get(self, request, vegetable_id):
        vegetable = get_object_or_404(self.model, pk=vegetable_id)
        # print(vegetable)               # seller_id
        # print(vegetable.item_name)     # 商品名
        form = ItemForm()
        return render(request, self.template_name, {'vegetable': vegetable, 'form': form})

    def post(self, request, vegetable_id):
        print('test_post')
        vegetable = get_object_or_404(self.model, pk=vegetable_id)
        form = ItemForm(request.POST, instance=vegetable)
        if form.is_valid():
            form.save()
            return redirect('seller:home')

        return render(request, self.template_name, {'vegetable': vegetable, 'form': form})

seller/templates/seller/create_item.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Create Item</title>
    <link rel="stylesheet" type="text/css" href="{% static 'seller/css/create_item.css' %}">
</head>
<body>
    <div class="h1">Create Item</div>
    <div class="form-fields">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div class="back-container">
        <a href="javascript:history.go(-1)" class="back-btn">戻る</a>
    </div>
</body>
</html>

seller/templates/seller/edit_item.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Edit Item</title>
    <link rel="stylesheet" type="text/css" href="{% static 'seller/css/create_item.css' %}">
</head>
<body>
    <div class="h1">Edit Item</div>
    <div class="form-fields">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">編集</button>
        </form>
    </div>
    <div class="back-container">
        <a href="javascript:history.go(-1)" class="back-btn">戻る</a>
    </div>
</body>
</html>

seller/templates/seller/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>出品者画面</title>
    <link rel="stylesheet" type="text/css" href="{% static 'seller/css/home.css' %}">
</head>
<body>
    <div class="wrap">
        <div class="header">
            <h1>野菜オンラインショップ（出品）</h1>
        </div>
        <div class="logout-container">
            <a href="{% url 'accounts:logout' %}" class="logout-btn">ログアウト</a>
        </div>
        <div class="personal-info">
            {% if user.profile_picture %}
            <img src="{{ user.profile_picture.url }}" alt="プロフィール画像">
            {% else %}
            <img src="{% static 'images/NoFace.jpg' %}" alt="プロフィール画像">
            {% endif %}
            <p>出品者名 : {{ user.last_name }} {{ user.first_name }}</p>
            <p>住所 : {{ seller.address}}</p>
            <a href="{% url 'accounts:edit_profile' %}" class="edit-profile-btn">プロフィールを編集する</a>
        </div>
        <a href="{% url 'seller:create_item' %}" class="submit-button">出品する</a>
        <h2>出品している野菜一覧</h2>
        <div class="product-list">
            {% for vegetable in vegetables %}
            <div class="product">
                <h3>野菜名：{{ vegetable.item_name }}</h3>
                <p>価格 : {{ vegetable.content_price|floatformat:"0" }}円</p>
                <a href="{% url 'seller:product_detail' vegetable_id=vegetable.id %}">詳細を見る</a>
            </div>
            {% endfor %}
        </div>
        <div class="toggle-mode-container">
            <a href="{% url 'buyer:home' %}" class="toggle-mode-btn">購入モード切替</a>
        </div>
</body>
</html>

seller/templates/seller/product_detail.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>商品詳細</title>
    <link rel="stylesheet" type="text/css" href="{% static 'seller/css/product_detail.css' %}">
</head>
<body>
    <h1>野菜詳細</h1>
    <div class="personal-info">
        {% if user.profile_picture %}
        <img src="{{ user.profile_picture.url }}" alt="プロフィール画像">
        {% else %}
        <img src="{% static 'images/NoFace.jpg' %}" alt="プロフィール画像">
        {% endif %}
        <p>出品者名 : {{ user.last_name }} {{ user.first_name }}</p>
        <p>住所 : {{ seller.address}}</p>
    </div>
    <div class="product-detail">
        <h3>商品名：{{ vegetable.item_name }}</h3>
        <p>品種名：{{ vegetable.item_type }}</p>
        <p>まとまりの内容個数：{{ vegetable.content_quantity }}</p>
        <p>まとまりの価格：{{ vegetable.content_price|floatformat:"0" }}円</p>
        <p>まとまりの総数：{{ vegetable.total_quantity }}</p>
        <a href="{% url 'seller:edit_item' vegetable_id=vegetable.id %}" class="edit-btn">編集</a>
    </div>
    <div class="back-container">
        <a href="javascript:history.go(-1)" class="back-btn">戻る</a>
    </div>
    <div class="comment-section">
        <h2>コメント</h2>
        {% for comment in vegetable.comments %}
        <div class="comment">
            <p>{{ comment.text }}</p>
            <button class="comment-edit-btn">編集</button>
        </div>
        {% endfor %}
    </div>
</body>
</html>

seller/templates/seller/seller_not_found.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register as Seller</title>
    <link rel="stylesheet" type="text/css" href="{% static 'seller/css/seller_not_found.css' %}">
</head>
<body>
    <h1>Register as Seller</h1>
    <p>出品者として登録がされていません。出品者モードに切り替えるには出品者として登録してください。</p>
    <a href="{% url 'accounts:edit_profile' %}" class="btn btn-primary">Settings</a>
    <div class="back-container">
        <a href="javascript:history.go(-1)" class="back-btn">戻る</a>
    </div>
</body>
</html>