accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path('signup/', views.SignupView.as_view(), name="signup"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path("edit_profile/", views.EditProfileView.as_view(), name="edit_profile"),
]

buyer/urls.py
from django.urls import path
from .views import (BuyerHomeView, VegetableListView, ProductDetailView,
                    PurchaseCompleteView, TransactionListView, TransactionDetailView,
                    GenreFirstView, GenreVegetableView, GenreDetailView, ErrorBCView, NothingProductView)

app_name = "buyer"

urlpatterns = [
    path("home/", BuyerHomeView.as_view(), name="home"),
    path('vegetable_list/', VegetableListView.as_view(), name='vegetable_list'),
    path('product/<int:vegetable_id>/', ProductDetailView.as_view(), name='product_detail'),
    path('genre/', GenreFirstView.as_view(), name='genre'),
    path('genre/genre_vegetable/', GenreVegetableView.as_view(), name='genre_vegetable'),
    path('genre/<str:genre_name>/', GenreDetailView.as_view(), name='genre_name'),
    path('purchase_complete/', PurchaseCompleteView.as_view(), name='purchase_complete'),
    path('transaction_list/', TransactionListView.as_view(), name='transaction_list'),
    path('transaction_list/<int:vegetable_id>/<uuid:transaction_id>/', TransactionDetailView.as_view(), name='transaction_detail'),
    path('blockchain_error/', ErrorBCView.as_view(), name='blockchain_error'),
    path('nothing_purchased_product/', NothingProductView.as_view(), name='nothing_purchased_product'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/accounts/')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('buyer/', include('buyer.urls')),
    path('seller/', include('seller.urls')),
]

seller/urls.py
from django.urls import path

from .views import SellerHomeView, CreateItemView, ProductDetailView, EditItemView

app_name = "seller"

urlpatterns = [
    path("home/", SellerHomeView.as_view(), name="home"),
    path('create/', CreateItemView.as_view(), name='create_item'),
    path('product/<int:vegetable_id>/', ProductDetailView.as_view(), name='product_detail'),
    path('edit/<int:vegetable_id>', EditItemView.as_view(), name='edit_item')
]

buyer/models.py
from django.db import models
from accounts.models import User

class Buyer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='buyer')
    address = models.CharField(max_length=200)
    favorite = models.CharField(max_length=100)

    def __str__(self):
        return str(self.user_id)

class Transaction(models.Model):
    purchase_id = models.CharField(max_length=100, unique=True)
    # user_id = models.CharField(max_length=100)
    # item_id = models.CharField(max_length=100)
    # purchase_date = models.DateTimeField()
    # purchase_price = models.DecimalField(max_digits=10, decimal_places=2)
    # quantity = models.IntegerField()
    purchase_status = models.CharField(max_length=50)
    payment_method = models.CharField(max_length=50)
    shipping_info = models.TextField()
    billing_info = models.TextField()
    additional_info = models.TextField(blank=True, null=True)

    def __str__(self):
        return str(self.purchase_id)

buyer/forms.py
from django import forms
from django.core.validators import MaxValueValidator, MinValueValidator

class PurchaseForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, label='購入数')

    def __init__(self, *args, **kwargs):
        max_quantity = kwargs.pop('max_quantity', None)
        super().__init__(*args, **kwargs)
        if max_quantity is not None:
            self.fields['quantity'].widget.attrs['max'] = max_quantity

    def clean_quantity(self):
        quantity = self.cleaned_data['quantity']
        max_quantity = self.fields['quantity'].widget.attrs.get('max')
        if max_quantity is not None and quantity > max_quantity:
            raise forms.ValidationError('在庫数を超える数量は選択できません。')
        return quantity

buyer/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .models import Buyer, Transaction
from seller.models import Vegetable, Product
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PurchaseForm
import uuid
from .blockchain.func.get_numTransaction import get_numtx
from .blockchain.func.get_detail import get_detail
from .blockchain.func.get_transactionInfo import get_tx
from .blockchain.func.set_transaction import set_info
import datetime
from django.db.models import Q


User = get_user_model()


class BuyerHomeView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'  # ログインしていない場合のリダイレクト先URL
    template_name = 'buyer/home.html'
    def get(self, request):
        return render(request, self.template_name)


class VegetableListView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'
    template_name = 'buyer/vegetable_list.html'
    def get(self, request):
        vegetables = Vegetable.objects.all()
        # print(vegetables)
        return render(request, self.template_name, {'vegetables': vegetables})


class ProductDetailView(LoginRequiredMixin, DetailView):
    login_url = '/accounts/login/'
    model = Vegetable
    template_name = 'buyer/product_detail.html'

    def get(self, request, vegetable_id):
        vegetable = get_object_or_404(Vegetable, pk=vegetable_id)
        form = PurchaseForm(initial={'max_quantity': vegetable.total_quantity})
        form.fields['quantity'].widget.attrs['max'] = vegetable.total_quantity
        return render(request, self.template_name, {'vegetable': vegetable, 'form': form})

    def post(self, request, vegetable_id):
        vegetable = get_object_or_404(Vegetable, pk=vegetable_id)

        form = PurchaseForm(request.POST, initial={'max_quantity': vegetable.total_quantity})
        if form.is_valid():
            purchase_id = str(uuid.uuid4())
            user = request.user.id
            item_id = vegetable_id
            quantity = form.cleaned_data['quantity']
            purchase_price = int(vegetable.content_price * quantity)
            purchase_status = '---'
            payment_method = '---'
            shipping_info = '---'
            billing_info = '---'
            additional_info = '---'
            transaction = Transaction.objects.create(
                purchase_id=purchase_id,
                purchase_status=purchase_status,
                payment_method=payment_method,
                shipping_info=shipping_info,
                billing_info=billing_info,
                additional_info=additional_info
            )
            transaction.save()
            try:
                set_info(purchase_id, str(user), str(item_id), str(purchase_price), str(quantity))
            except:
                pass
            # 在庫数と購入数を比較して、在庫を超えないようにする
            if quantity <= vegetable.total_quantity:
                # 在庫数を更新
                vegetable.total_quantity -= quantity
                vegetable.save()
                return redirect('buyer:purchase_complete')

        return render(request, self.template_name, {'vegetable': vegetable, 'form': form})


class PurchaseCompleteView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'
    template_name = 'buyer/purchase_complete.html'
    def get(self, request):
        return render(request, self.template_name)


class TransactionListView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'
    template_name = 'buyer/transaction_list.html'

    def get(self, request):
        user = request.user.id
        try:
            tx_list = get_tx(str(user))
            l = []
            try:
                for vege in tx_list['output']:
                    l.append(vege['item_id'])
                vegetables = Vegetable.objects.filter(id__in=l)
                vegetable_and_transaction = zip(vegetables, tx_list['output'])
                return render(request, self.template_name, {'vegetable_and_transaction': vegetable_and_transaction})
            except Exception as e: # 購入していない
                return render(request, 'buyer/nothing_purchased_products.html')
        except Exception as e: # blockchain api error
            return render(request, 'buyer/bc_err.html')


class TransactionDetailView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'
    template_name = 'buyer/transaction_detail.html'

    def get(self, request, vegetable_id, transaction_id):
        vegetable = get_object_or_404(Vegetable, pk=vegetable_id)
        tx_detail = get_detail(transaction_id)
        timestamp = int(tx_detail['output']['purchase_date'][:10])
        dt = datetime.datetime.fromtimestamp(timestamp)
        tx_detail['output']['purchase_date'] = str(dt)
        return render(request, self.template_name, {'vegetable': vegetable, 'tx_detail': tx_detail['output']})


class GenreFirstView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'
    template_name = 'buyer/genre.html'
    def get(self, request):
        products = Product.objects.all()
        return render(request, self.template_name, {'products': products})


class GenreVegetableView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'
    template_name = 'buyer/genre_vegetable.html'
    def get(self, request):
        products = Product.objects.all()
        return render(request, self.template_name, {'products': products})


class GenreDetailView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'
    template_name = 'buyer/vegetable_list.html'
    def get(self, request, genre_name):
        if '-' in genre_name:
            left_side, right_side = genre_name.split("-")
            grains_items = Product.objects.filter(Q(main_genre_name=left_side) & Q(sub_genre_name=right_side)).values_list("item_name", flat=True)
        else:
            grains_items = Product.objects.filter(main_genre_name=genre_name).values_list("item_name", flat=True)
        vegetables = Vegetable.objects.filter(item_name__in=grains_items)
        return render(request, self.template_name, {'vegetables': vegetables})


class ErrorBCView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'
    template_name = 'buyer/bc_err.html'
    def get(self, request):
        return render(request, self.template_name)

class NothingProductView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'
    template_name = 'buyer/nothing_purchased_products.html'
    def get(self, request):
        return render(request, self.template_name)

buyer/templates/buyer/bc_err.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>ブロックチェーンに異常があります</title>
    <link rel="stylesheet" type="text/css" href="{% static 'buyer/css/vegetable_list.css' %}">
</head>
<body>
    <div class="header">
        <h1>ブロックチェーンに異常があります</h1>
    </div>
    <div class="logout-container">
        <a href="{% url 'accounts:logout' %}" class="logout-btn">ログアウト</a>
    </div>
    <div class="back-container">
        <a href="javascript:history.go(-1)" class="back-btn">戻る</a>
    </div>
</body>
</html>

buyer/templates/buyer/genre.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Grid Layout with Buttons</title>
    <link rel="stylesheet" type="text/css" href="{% static 'buyer/css/genre.css' %}">
</head>
<body>
    <div class="grid-container">
        <div class="grid-item">
            <a href="{% url 'buyer:genre_name' genre_name='Grains' %}" class="large-button"> 穀物類 </a>
        </div>
        <div class="grid-item">
            <a href="{% url 'buyer:genre_vegetable' %}" class="large-button"> 野菜類 </a>
        </div>
        <div class="grid-item">
            <a href="{% url 'buyer:genre_name' genre_name='Fruits' %}" class="large-button"> 果物類 </a>
        </div>
        <div class="grid-item">
            <a href="{% url 'buyer:genre_name' genre_name='Others' %}" class="large-button"> その他 </a>
        </div>
    </div>
    <div class="back-container">
        <a href="#" onclick="window.history.back();" class="back-btn">戻る</a>
    </div>
</body>
</html>

buyer/templates/buyer/genre_vegetable.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Grid Layout with Buttons</title>
    <link rel="stylesheet" type="text/css" href="{% static 'buyer/css/genre.css' %}">
</head>
<body>
    <div class="grid-container">
        <div class="grid-item">
            <a href="{% url 'buyer:genre_name' genre_name='Vegetables-LeafStem' %}" class="large-button"> 葉茎菜類 </a>
        </div>
        <div class="grid-item">
            <a href="{% url 'buyer:genre_name' genre_name='Vegetables-Root' %}" class="large-button"> 根菜類 </a>
        </div>
        <div class="grid-item">
            <a href="{% url 'buyer:genre_name' genre_name='Vegetables-Fruit' %}" class="large-button"> 果菜類 </a>
        </div>
        <div class="grid-item">
            <a href="{% url 'buyer:genre_name' genre_name='Vegetables-Others' %}" class="large-button"> その他 </a>
        </div>
    </div>
    <div class="back-container">
        <a href="#" onclick="window.history.back();" class="back-btn">戻る</a>
    </div>
</body>
</html>

buyer/templates/buyer/home.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>購入者画面</title>
    <link rel="stylesheet" type="text/css" href="{% static 'buyer/css/home.css' %}">
</head>
<style>
    .productlist-all-btn {
        background: linear-gradient(to top, rgba(217, 175, 217, 0.7) 0%, rgba(151, 217, 225, 0.7) 100%),
        url("{% static 'buyer/img/product_all.jpg' %}");
        background-repeat: no-repeat;
        background-position: center;
        color: #ffffff;
        font-weight: bold;
        padding: 100px 100px;
        border: none;
        border-radius: 5px;
        text-decoration: none;
        cursor: pointer;
        z-index: 9999;
    }

    .productlist-selected-btn {
        background: linear-gradient(to top, rgba(217, 175, 217, 0.7) 0%, rgba(151, 217, 225, 0.7) 100%),
        url("{% static 'buyer/img/product_selected.jpg' %}");
        background-repeat: no-repeat;
        background-position: center;
        color: #ffffff;
        font-weight: bold;
        padding: 100px 100px;
        border: none;
        border-radius: 5px;
        text-decoration: none;
        cursor: pointer;
        z-index: 9999;
    }

</style>
<body>
    <div class="wrap">
        <div class="header">
            <h1>野菜オンラインショップ（購入）</h1>
        </div>
        <div class="logout-container">
            <a href="{% url 'accounts:logout' %}" class="logout-btn">ログアウト</a>
        </div>
        <div class="personal-info">
            {% if user.profile_picture %}
            <img src="{{ user.profile_picture.url }}" alt="プロフィール画像">
            {% else %}
            <img src="{% static 'images/NoFace.jpg' %}" alt="プロフィール画像">
            {% endif %}
            <p>出品者名 : {{ user.last_name }} {{ user.first_name }}</p>
            <p>住所 : {{ seller.address}}</p>
            <a href="{% url 'accounts:edit_profile' %}" class="edit-profile-btn">プロフィールを編集する</a>
        </div>
        <div class="centered-content">
            <a href="{% url 'buyer:transaction_list' %}" class="purchase-list-btn">購入一覧表示</a>
            <div class="search-box">
                <input type="text" placeholder="検索キーワードを入力してください" size="35">
                <button type="submit">検索</button>
            </div>
        </div>
        <div class="productlist-all-container">
            <a href="{% url 'buyer:vegetable_list' %}" class="productlist-all-btn">出品商品一覧</a>
            <a href="{% url 'buyer:genre' %}" class="productlist-selected-btn">ジャンルで選ぶ</a>
        </div>
        <div class="toggle-mode-container">
            <a href="{% url 'seller:home' %}" class="toggle-mode-btn">出品モード切替</a>
        </div>
</body>
</html>

buyer/templates/buyer/nothing_purchased_products.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>購入している商品がありません</title>
    <link rel="stylesheet" type="text/css" href="{% static 'buyer/css/vegetable_list.css' %}">
</head>
<body>
    <div class="header">
        <h1>購入している商品がありません</h1>
    </div>
    <div class="logout-container">
        <a href="{% url 'accounts:logout' %}" class="logout-btn">ログアウト</a>
    </div>
    <div class="back-container">
        <a href="javascript:history.go(-1)" class="back-btn">戻る</a>
    </div>
</body>
</html>

buyer/templates/buyer/product_detail.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>商品詳細</title>
    <link rel="stylesheet" type="text/css" href="{% static 'buyer/css/product_detail.css' %}">
    <script src="{% static 'buyer/js/popup.js' %}"></script>
</head>
<body>
    <h1>野菜詳細</h1>
    <div class="personal-info">
        {% if user.profile_picture %}
        <img src="{{ user.profile_picture.url }}" alt="プロフィール画像">
        {% else %}
        <img src="{% static 'images/NoFace.jpg' %}" alt="プロフィール画像">
        {% endif %}
        <p>出品者名 : {{ user.last_name }} {{ user.first_name }}</p>
        <p>住所 : {{ seller.address}}</p>
        <button type="button" class="purchase-btn" onclick="openPopup()">購入</buttton>
    </div>
    <div id="popup" class="popup-content" style="display: none;">
        <button class="close-btn" onclick="closePopup()">X</button>
        <p class="popup-text">確認</p>
        <div class="form-fields">
            <form method="post" , id="purchaseForm">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="button" id="calculateButton">金額計算</button>
                <p id="totalPrice"></p>
                <input type="submit" value="購入" class="popup-button">
            </form>
        </div>
    </div>
    <script>
        function openPopup() {
            document.getElementById("popup").style.display = "block";
        }

        function closePopup() {
            document.getElementById("popup").style.display = "none";
        }
        document.getElementById("calculateButton").addEventListener("click", function () {
            const form = document.getElementById("purchaseForm");
            const quantity = parseInt(form.quantity.value);
            const contentPrice = parseFloat("{{ vegetable.content_price }}");
            const totalPrice = quantity * contentPrice;
            document.getElementById("totalPrice").innerText = "合計金額：" + totalPrice + "円";
        });
    </script>
    <div class="product-detail">
        <h3>商品名：{{ vegetable.item_name }}</h3>
        <p>品種名：{{ vegetable.item_type }}</p>
        <p>まとまりの内容個数：{{ vegetable.content_quantity }}</p>
        <p>まとまりの価格：{{ vegetable.content_price|floatformat:"0" }}円</p>
        <p>まとまりの総数：{{ vegetable.total_quantity }}</p>
    </div>
    <div class="comment-section">
        <h2>コメント</h2>
        {% for comment in vegetable.comments %}
        <div class="comment">
            <p>{{ comment.text }}</p>
        </div>
        {% endfor %}
    </div>
    <div class="back-container">
        <a href="#" onclick="window.history.back();" class="back-btn">戻る</a>
    </div>
</body>
</html>

buyer/templates/buyer/purchase_complete.html
<h1>購入が完了しました！</h1>
<a href="{% url 'buyer:home' %}">一覧に戻る</a>

buyer/templates/buyer/transaction_detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>購入した商品の情報</title>
    <link rel="stylesheet" type="text/css" href="{% static 'buyer/css/transaction_detail.css' %}">
</head>
<body>
    <div class="header">
        <h1>購入した商品の情報</h1>
    </div>
    <div class="product-list">
        <ul>
            <li class="product">
                <h3>{{ vegetable.item_name }}</h3>
                <p>出品者: {{ vegetable.seller.user.last_name }} {{ vegetable.seller.user.first_name }} さん</p>
                <p>購入日時: {{ tx_detail.purchase_date }}</p>
                <p>購入個数(セット): {{ tx_detail.quantity }}</p>
                <p>金額: {{ tx_detail.purchase_price }}円</p>
                <a href="#" class="cancel-btn">キャンセル</a>
            </li>
        </ul>
    </div>
    <div class="back-container">
        <a href="javascript:history.go(-1)" class="back-btn">戻る</a>
    </div>
</body>
</html>

buyer/templates/buyer/transaction_list.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>購入商品一覧</title>
    <link rel="stylesheet" type="text/css" href="{% static 'buyer/css/vegetable_list.css' %}">
</head>
<body>
    <div class="header">
        <h1>購入商品一覧</h1>
    </div>
    <div class="logout-container">
        <a href="{% url 'accounts:logout' %}" class="logout-btn">ログアウト</a>
    </div>
    <div class="product-list">
        <ul>
            {% for vegetable, element in vegetable_and_transaction %}
            <li class="product">
                <h3>{{ vegetable.item_name }}</h3>
                <a href="{% url 'buyer:transaction_detail' vegetable_id=vegetable.id transaction_id=element.purchase_id %}" >詳細</a></p>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="back-container">
        <a href="javascript:history.go(-1)" class="back-btn">戻る</a>
    </div>
</body>
</html>

buyer/templates/buyer/vegetable_list.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>出品商品一覧</title>
    <link rel="stylesheet" type="text/css" href="{% static 'buyer/css/vegetable_list.css' %}">
</head>
<body>
    <div class="header">
        <h1>出品商品一覧</h1>
    </div>
    <div class="logout-container">
        <a href="{% url 'accounts:logout' %}" class="logout-btn">ログアウト</a>
    </div>
    <div class="product-list">
        <ul>
            {% for vegetable in vegetables %}
            <li class="product">
                <h3>{{ vegetable.item_name }}</h3>
                <p>品種: {{ vegetable.item_type }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;出品者: {{ vegetable.seller.user.last_name }} {{ vegetable.seller.user.first_name }} さん</p>
                <p>内容量(個数): {{ vegetable.content_quantity }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;価格/袋: {{ vegetable.content_price|floatformat:"0" }}円
                <a href="{% url 'buyer:product_detail' vegetable_id=vegetable.id %}" >詳細</a></p>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="back-container">
        <a href="javascript:history.go(-1)" class="back-btn">戻る</a>
    </div>
</body>
</html>