accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path('signup/', views.SignupView.as_view(), name="signup"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path("edit_profile/", views.EditProfileView.as_view(), name="edit_profile"),
]

buyer/urls.py
from django.urls import path
from .views import (BuyerHomeView, VegetableListView, ProductDetailView,
                    PurchaseCompleteView, TransactionListView, TransactionDetailView,
                    GenreFirstView, GenreVegetableView, GenreDetailView, ErrorBCView, NothingProductView)

app_name = "buyer"

urlpatterns = [
    path("home/", BuyerHomeView.as_view(), name="home"),
    path('vegetable_list/', VegetableListView.as_view(), name='vegetable_list'),
    path('product/<int:vegetable_id>/', ProductDetailView.as_view(), name='product_detail'),
    path('genre/', GenreFirstView.as_view(), name='genre'),
    path('genre/genre_vegetable/', GenreVegetableView.as_view(), name='genre_vegetable'),
    path('genre/<str:genre_name>/', GenreDetailView.as_view(), name='genre_name'),
    path('purchase_complete/', PurchaseCompleteView.as_view(), name='purchase_complete'),
    path('transaction_list/', TransactionListView.as_view(), name='transaction_list'),
    path('transaction_list/<int:vegetable_id>/<uuid:transaction_id>/', TransactionDetailView.as_view(), name='transaction_detail'),
    path('blockchain_error/', ErrorBCView.as_view(), name='blockchain_error'),
    path('nothing_purchased_product/', NothingProductView.as_view(), name='nothing_purchased_product'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/accounts/')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('buyer/', include('buyer.urls')),
    path('seller/', include('seller.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (BaseUserManager,
                                        AbstractBaseUser,
                                        PermissionsMixin)
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    def _create_user(self, email, account_id, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, account_id=account_id, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email, account_id, password=None, **extra_fields):
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        extra_fields.setdefault('is_seller', False)
        return self._create_user(
            email=email,
            account_id=account_id,
            password=password,
            **extra_fields,
        )

    def create_superuser(self, email, account_id, password, **extra_fields):
        extra_fields['is_active'] = True
        extra_fields['is_staff'] = True
        extra_fields['is_superuser'] = True
        extra_fields['is_seller'] = True
        return self._create_user(
            email=email,
            account_id=account_id,
            password=password,
            **extra_fields,
        )


class User(AbstractBaseUser, PermissionsMixin):

    account_id = models.CharField(
        verbose_name=_("account_id"),
        unique=True,
        max_length=10
    )
    email = models.EmailField(
        verbose_name=_("email"),
        unique=True
    )
    first_name = models.CharField(
        verbose_name=_("first_name"),
        max_length=150,
        null=True,
        blank=False
    )
    last_name = models.CharField(
        verbose_name=_("last_name"),
        max_length=150,
        null=True,
        blank=False
    )
    birth_date = models.DateField(
        verbose_name=_("birth_date"),
        blank=True,
        null=True
    )
    is_superuser = models.BooleanField(
        verbose_name=_("is_superuer"),
        default=False
    )
    is_staff = models.BooleanField(
        verbose_name=_('staff status'),
        default=False,
    )
    is_seller = models.BooleanField(
        verbose_name=_('is_seller'),
        default=False,
    )
    is_active = models.BooleanField(
        verbose_name=_('active'),
        default=True,
    )
    created_at = models.DateTimeField(
        verbose_name=_("created_at"),
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        verbose_name=_("updateded_at"),
        auto_now=True
    )
    address = models.CharField(
        max_length=200,
        blank=True,
        null=True
    )
    profile_picture = models.ImageField(
        upload_to='profile_pics/',
        blank=True,
        null=True
    )

    objects = UserManager()

    USERNAME_FIELD = 'account_id' # ログイン時、ユーザー名の代わりにaccount_idを使用
    REQUIRED_FIELDS = ['email']  # スーパーユーザー作成時にemailも設定する

    def __str__(self):
        return self.account_id

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.utils.translation import gettext_lazy as _
from django import forms
from .models import User


class SignUpForm(UserCreationForm):
    is_seller = forms.BooleanField(required=False, label=_('出品します。'), widget=forms.CheckboxInput(attrs={'class': 'checkbox-class'}))

    class Meta:
        model = User
        fields = ('account_id', 'email', 'last_name', 'first_name', 'birth_date', 'is_seller')

        # フィールドのラベルを日本語に設定
        labels = {
            'account_id': _('アカウントID'),
            'email': _('メールアドレス'),
            'last_name': _('姓(English)'),
            'first_name': _('名(English)'),
            'birth_date': _('生年月日'),
            'is_seller': _('出品します。')
        }


# ログインフォームを追加
class LoginFrom(AuthenticationForm):
    class Meta:
        model = User


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'address', 'profile_picture')

accounts/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, CreateView
from django.contrib.auth.views import LoginView as BaseLoginView,  LogoutView as BaseLogoutView
from django.urls import reverse_lazy
from .forms import SignUpForm, LoginFrom, UserProfileForm
from buyer.models import Buyer
from seller.models import Seller
from django.views import View
from .forms import UserProfileForm
from django.contrib.auth.mixins import LoginRequiredMixin


class IndexView(TemplateView):
    template_name = "accounts/index.html"


class SignupView(CreateView):
    form_class = SignUpForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("accounts:index")

    def form_valid(self, form):
        response = super().form_valid(form)

        is_seller = form.cleaned_data['is_seller']

        # Buyerモデルのインスタンスを作成して保存する
        buyer = Buyer.objects.create(user=self.object, address="---", favorite="---")
        if is_seller:
            # ユーザーが出品者の場合、Sellerモデルのインスタンスを作成して保存する
            seller = Seller.objects.create(user=self.object, address="---")

        return response


class LoginView(BaseLoginView):
    form_class = LoginFrom
    template_name = "accounts/login.html"
    success_url = reverse_lazy('buyer:home')


class LogoutView(BaseLogoutView):
    success_url = reverse_lazy("accounts:index")


class EditProfileView(LoginRequiredMixin, View):
    template_name = 'accounts/edit_profile.html'

    def get(self, request):
        form = UserProfileForm(instance=request.user)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = UserProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:view_profile')
        return render(request, self.template_name, {'form': form})

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block title %}
<div class="h1">Edit Profile</div>
{% endblock %}

{% block content %}
<div>
    <br>
    <form method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-fields">
            {% for field in form %}
            <div class="form-field">
                {{ field.label }}
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %}
        </div>
        <div class="mt-3">
            <button type="submit">保存</button>
        </div>
        <div class="back-container">
            <a href="javascript:history.go(-1)" class="back-btn">戻る</a>
        </div>
    </form>
</div>
<style>
    .form-fields {
        text-align: center;
    }

    .form-field {
        margin-bottom: 10px;
    }

    .back-container {
        position: absolute;
        top: 30px;
        left: 30px;
    }

    .back-btn {
        background-color: #dc3545;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        text-decoration: none;
        cursor: pointer;
    }

</style>
{% endblock %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{% if user.is_authenticated %}
<div class="h1">MyPage</div>
{% else %}
<div class="h1">Main</div>
{% endif %}
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="h2">Welcome {{ user.first_name }} {{ user.last_name }}</div>
<a href="{% url 'accounts:logout' %}" class="btn btn-primary">Logout</a>
{% else %}
<a href="{% url 'accounts:signup' %}" class="btn btn-primary">Signup</a>
<a href="{% url 'accounts:login' %}" class="btn btn-primary">Login</a>
{% endif %}
<style>
    body {
        background-image: url("{% static 'images/blueberry.jpg' %}");
        background-size: cover;
    }

</style>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}
<div class="h1">Login</div>
{% endblock %}

{% block content %}
<style>
    .form-fields {
        text-align: center;
    }

    .form-field {
        margin-bottom: 10px;
    }

</style>

<div class="form-fields">
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}

        {% for field in form %}
        <div class="form-field">
            {{ field.label }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}

        <div class="mt-3">
            <button type="submit" class="btn btn-primary">Login</button>
            <a href="{% url 'accounts:index' %}" class="btn btn-secondary">Back</a>
        </div>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}
<div class="h1">Create account</div>
{% endblock %}

{% block content %}
<div>
    <br>
    <form method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-fields">
            {% for field in form %}
            <div class="form-field">
                {{ field.label }}
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %}
        </div>
        <div class="mt-3">
            <button type="submit" class="btn btn-primary">Create</button>
            <a href="{% url 'accounts:index' %}" class="btn btn-secondary">Back</a>
        </div>
    </form>
</div>
<style>
    .form-fields {
        text-align: center;
    }

    .form-field {
        margin-bottom: 10px;
    }

</style>
{% endblock %}